version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=CurrencyDb
      - POSTGRES_USER=CurrencyAppUser
      - POSTGRES_PASSWORD=development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U CurrencyAppUser -d CurrencyDb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: